[tools]
# for mise Completion: https://usage.jdx.dev/
usage = "latest"
# Shell Tools
chezmoi = "latest"
starship = "latest"
"aqua:rossmacarthur/sheldon" = "latest"
neovim = "latest"
tree-sitter = "latest"
fzf = "latest"
bat = "latest"
eza = "latest"
ripgrep = "latest"
lazygit = "latest"
# Git Tools
github-cli = "latest"
ghq = "latest"
# Language Tools
node = "latest"
"npm:@antfu/ni" = "latest"
pnpm = "latest"
deno = "latest"

uv = "latest"
rust = "latest"

[settings]
experimental = true
